module.exports = {
  projects: [
    '<rootDir>/libs/calendar',
    '<rootDir>/apps/calendar',
    '<rootDir>/libs/calendar/api',
    '<rootDir>/libs/shared/shared-api',
    '<rootDir>/libs/shared/api',
    '<rootDir>/libs/calendar/view',
    '<rootDir>/libs/calendar/features/view',
    '<rootDir>/libs/calendar/features/dashboard',
    '<rootDir>/apps/calendar-app',
    '<rootDir>/libs/shared/modal',
    '<rootDir>/libs/calendar/dates',
    '<rootDir>/libs/calendar/types',
    '<rootDir>/libs/shared/theme',
    '<rootDir>/libs/shared/view',
    '<rootDir>/libs/calendar/features/home',
    '<rootDir>/libs/calendar/features/calendar',
  ],
};
